### ISSUE TITLE
gtest를 위한 컴파일이 안됨

### ISSUE THREAD

**Issue by kosh7707** [kosh7707/new_unix_musicplayer#34]
현재 makefile에서 CXX := gcc -std=c11을 추가하고 실행하면 컴파일은 가능하나 
version이 c11이라 c++을 사용하는 googletest는 컴파일이 안되네요 ㅎ;;

만약 컴파일이 당장 필요한 상황이시라면 makefile에서 CXX := gcc -std=c11를 추가하고 실행해주세요
(현재는 $(CXX) --> g++ 로 나옵니다.)

**Comment by namhyung123** [comment]
@kosh7707 저는 아예 갈아 엎고 로컬에서 새로 하니까 컴파일이 되네요 뭐지??

**Comment by namhyung123** [comment]
append, append_left 까지 test 통과 나왔어요

**Comment by kosh7707** [comment]
??? push plz

**Comment by namhyung123** [comment]
로컬에서 테스트만 하려고 pull안하고 그냥 master 브랜치에다가 했더니 push 가 안되네요

**Comment by kosh7707** [comment]
일단 master branch 올라온 거 있으니까 그거 확인좀 해봐야할듯해요 ㅎ..
저희 default가 master가 아니라 main이라 거기 맞춰야 할 것 같아요

**Comment by kosh7707** [comment]
제가 지금 개발할때는 이렇게해요
branch를 leader에 둔 상태에서 git push -u origin leader 하면 leader branch에 push가 됩니다.
여기서 compare & pull request 버튼 생기면 그때 main으로 merge를 해여

**Comment by namhyung123** [comment]
일단 한번 pull 하고나서 수정한거 다시 넣어보고 컴파일 되나 안되나 해볼게요

**Comment by namhyung123** [comment]
아 pull request 안하고 push만 했는데 파일이 보이나 보네요

**Comment by kosh7707** [comment]
push를 origin master에 하시면 remote repository에  새 branch가 생성됩니다.

**Comment by kosh7707** [comment]
merge가 안되는 이유는 master가 main과는 전혀 상관없는 곳에서 발생해서 그럴거에요

**Comment by kosh7707** [comment]
그래도 덕분에 뭐가 문젠지 알거같습니다. 역시 같이 하는게 좋네요 ㅎ

**Comment by namhyung123** [comment]
앗 저도요ㅋㅋ 저 위에 뜨는 push한거 취소는 어떻게 하나요?

**Comment by kosh7707** [comment]
master branch 만드신거 push 취소하고 싶으시면 
https://www.lesstif.com/gitbook/git-delete-remote-branch-20776547.html
이거 보시면 괜찮을거에요.

**Comment by kosh7707** [comment]
이번 push로 해결하였습니다. main branch를 참고해주세요
