### ISSUE TITLE
label이 설정 안되요 ㅠㅠㅠ

### ISSUE THREAD

**Issue by namhyung123** [kosh7707/new_unix_musicplayer#35]
톱니바퀴가 안보여요

**Comment by kosh7707** [comment]
잠시만요??????

**Comment by namhyung123** [comment]
안돼요

**Comment by kosh7707** [comment]
제가 저 링크 따라해보면 매니저 추가된게 아니라 초대링크가 갔다고 뜨거든요? 혹시 뭐 온거 있으신가요?
https://github.com/kosh7707/new_unix_musicplayer/invitations

**Comment by namhyung123** [comment]
오 톱니바쿠 나오네요 된거 같습니다

**Comment by kosh7707** [comment]
굿;;
