### ISSUE TITLE
push 취소

### ISSUE THREAD

**Issue by namhyung123** [kosh7707/new_unix_musicplayer#36]
<img width="924" alt="1" src="https://user-images.githubusercontent.com/104840762/170323982-0bfb94b2-7df0-4a20-8a99-7a64745d5f94.png">

**Comment by kosh7707** [comment]
그냥 pull request 넣으시면 제가 손수 취소하겠습니다 ㅎ.

**Comment by namhyung123** [comment]
저거 pull request가 안먹혀요 ㅠㅠ

**Comment by namhyung123** [comment]
<img width="917" alt="2" src="https://user-images.githubusercontent.com/104840762/170324986-738abedc-ed6b-48ad-b744-bce176dc37f7.png">
밑에 내려가도 아무 버튼이 없네요

**Comment by kosh7707** [comment]
master branch를 삭제했는데 아직뜨나요?

**Comment by namhyung123** [comment]
네 계속 보이네요 제 로컬에서는 master 브랜치가 남아있긴한데

**Comment by namhyung123** [comment]
먼저 브랜치 삭제하다가 저 노란색 안없어질거같아서 삭제할지말지 고민되네요

**Comment by kosh7707** [comment]
로컬에서 git fetch 하시고 main이랑 merge하시면 pr을 할 수 있게 될거같네요. 근데 걍 두고 익숙해지시는게 ㅎㅎ

**Comment by namhyung123** [comment]
그냥 냅두고 해야겠네요

**Comment by kosh7707** [comment]
굿.
