### ISSUE TITLE
clear() isn't working.... in Multiple Pointer

### ISSUE THREAD

**Issue by namhyung123** [kosh7707/new_unix_musicplayer#42]
//test_linkedlist.c
TEST(TestLinkedList, Clear){
    //clear_testcase
    int NUM_OF_MUSIC = 3;
    char** music_titles = NULL;
    music_titles = (char**)malloc(sizeof(char*) * NUM_OF_MUSIC);
    for (int i=0; i < NUM_OF_MUSIC; i++){
        music_titles[i] = (char*)malloc(sizeof(char) * MAX_TITLE_SIZE);
    }
    music_titles[0] = (char*)"Hello";
    music_titles[1] = (char*)"Enemy";
    music_titles[2] = (char*)"abc";
    append(sizeof(music_titles[0]), music_titles[0]);
    append(sizeof(music_titles[1]), music_titles[1]);
    append(sizeof(music_titles[2]), music_titles[2]);
    clear();
    EXPECT_EQ(empty(), true);
}

//linkedlist.c
void clear(){
    //재생 목록을 비움
    Node* temp = _head;
    while(temp != NULL){
        temp = temp->next;
        free(_head);
        _head = temp;
    }
    printf("LinkedList is cleared!\n");
};

**Comment by namhyung123** [comment]
<img width="464" alt="6" src="https://user-images.githubusercontent.com/104840762/170536301-6f43094c-4896-4974-b63d-0bae501328e7.png">
Clions 에서는 작동합니다??

**Comment by namhyung123** [comment]
하ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ 이상한 오타때문에 안되는거였네요
안되는게 말이 안되는데 어쩐지 ... 3시간 버렸습니다

**Comment by kosh7707** [comment]
새벽 잠이 없으시군요..? 새벽 3시에 ㄷㄷ; 수고하셨습니다.
