### ISSUE TITLE
linkedlist의 print() 함수가 제대로 작동 안하네요

### ISSUE THREAD

**Issue by kosh7707** [kosh7707/new_unix_musicplayer#47]
![image](https://user-images.githubusercontent.com/65238064/170621587-d9703fa7-d2d7-48de-b292-08ac132805ba.png)
확인해보겠습니다

**Comment by kosh7707** [comment]
![image](https://user-images.githubusercontent.com/65238064/170621849-57f38718-6de7-4759-9b36-824401b36c20.png)
문제가 뭐였냐면
![image](https://user-images.githubusercontent.com/65238064/170621903-95e73492-8c7a-4f54-96cd-f8e95f86198f.png)
이렇게 newNode->data 부분에 malloc을 해주시고 strcpy를 쓰셨어야 했습니다.
원래 하시던대로 new_Node->data = new_data;를 하시면 shallow copy가 일어나서 원치않은 결과가 나옵니다.

**Comment by kosh7707** [comment]
같은 방법으로 append_left도 수정하였습니다.

**Comment by namhyung123** [comment]
어쩐지 계속 free를 해도 data가 남아있더군요 원인이 이거 였네요

**Comment by namhyung123** [comment]
<img width="284" alt="8" src="https://user-images.githubusercontent.com/104840762/170639370-9b57f11c-745c-4668-8512-88ae3042168d.png">
수정 전
<img width="261" alt="9" src="https://user-images.githubusercontent.com/104840762/170639396-86ac8250-0833-47e4-954d-3614a8d494ee.png">
수정 후 

data 잘 사라지는거 확인했습니다

**Comment by namhyung123** [comment]
clear() TEST 파일 만들때 segmentation fault 이것 때문인거같네요. 해결완료
