### ISSUE TITLE
Bug in linkedlist.c delete_by_data()

### ISSUE THREAD

**Issue by kosh7707** [kosh7707/new_unix_musicplayer#58]
![image](https://user-images.githubusercontent.com/65238064/170899211-ec434423-118d-46a0-9bad-18a3c3c426e7.png)

![image](https://user-images.githubusercontent.com/65238064/170899224-b821f953-f39d-4ec2-96bf-2a8c71b238a6.png)

delete_by_data(char*)가 현재 제대로 작동하고 있지 않습니다.

**Comment by kosh7707** [comment]
![image](https://user-images.githubusercontent.com/65238064/170899465-562ff2c3-fabb-4da5-9c4b-0a9846afd86e.png)
![image](https://user-images.githubusercontent.com/65238064/170899476-13714633-5809-48f4-8df4-5f2e0182439a.png)

temp->data와 data를 단순히 ==로 비교하면 포인터비교가 됩니다.
for로 한글자씩 비교하거나, strcmp를 사용하셔야합니다.

**Comment by namhyung123** [comment]
확인했습니다.  data 할당 전에는 node->data = 값 을 이용한 방식이라 저게 작동했지만 할당 후는 저런 유형들은 다 strcmp나 strcpy 등을 써야 작동할겁니다. 이따가 이런 유형들이 더 있으면 찾아보고 수정해서 push할게요
